# -*- coding: utf-8 -*-
"""COVID-19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g4th8WOrMtkLBYZkt5_6b2UGNx5szYAG
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.title("COVID-19感染データダッシュボード")

# COVID-19感染データを読み込む（例としてCSVファイルを使用）
data_url = "https://covid.ourworldindata.org/data/owid-covid-data.csv"
data = pd.read_csv(data_url)

# データのプレビューを表示
st.write("データのプレビュー")
st.dataframe(data.head())

# 国を選択するセレクトボックスを表示
countries = data['location'].unique()
selected_country = st.selectbox("国を選択してください", countries)

# 選択された国の感染データをフィルタリング
country_data = data[data['location'] == selected_country]

# グラフ：日毎の新規感染者数を表示
st.subheader(f"{selected_country}の日毎の新規感染者数")
fig_new_cases = px.line(country_data, x='date', y='new_cases', title=f"{selected_country}の日毎の新規感染者数")
st.plotly_chart(fig_new_cases)

# グラフ：日毎の死亡者数を表示
st.subheader(f"{selected_country}の日毎の死亡者数")
fig_new_deaths = px.line(country_data, x='date', y='new_deaths', title=f"{selected_country}の日毎の死亡者数")
st.plotly_chart(fig_new_deaths)

# グラフ：総感染者数と総死亡者数を表示
st.subheader(f"{selected_country}の総感染者数と総死亡者数")
fig_total_cases_deaths = px.line(country_data, x='date', y=['total_cases', 'total_deaths'],
                                 title=f"{selected_country}の総感染者数と総死亡者数")
st.plotly_chart(fig_total_cases_deaths)

from google.colab import drive
drive.mount('/content/drive')